[project]
name = "censusdis-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "censusdis>=1.4.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "tdd-guard-pytest>=0.1.2",
]
